repos:
- repo: omry/omegaconf
  backlog_url: https://omry.github.io/omegaconf/backlog.json
- repo: hydra-ecosystem/hydra
  backlog_url: https://raw.githubusercontent.com/hydra-ecosystem/hydra/backlog-atlas/backlog.json
- repo: omry/backlog-atlas
  backlog_url: https://omry.github.io/backlog-atlas/backlog.json
